# Khenzo Termux colors
background:     #0b0f14
foreground:     #e6edf3
cursor:         #3fb950

color0:         #0b0f14
color1:         #ff7b72
color2:         #3fb950
color3:         #d29922
color4:         #58a6ff
color5:         #bc8cff
color6:         #39c5cf
color7:         #e6edf3
color8:         #484f58
color9:         #ffa198
color10:        #56d364
color11:        #e3b341
color12:        #79c0ff
color13:        #d2a8ff
color14:        #56d4dd
color15:        #ffffff
